version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=postgresql://postgres:password@db:5432/petforce_development
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               bundle exec rails db:create db:migrate &&
               bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
      - tmp:/rails/tmp
    depends_on:
      - redis
      - db

  worker:
    build: .
    command: bundle exec sidekiq
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=postgresql://postgres:password@db:5432/petforce_development
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
      - tmp:/rails/tmp
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
  bundle_cache:
  node_modules:
  tmp: 